"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { Button, ButtonLink } from "@/src/components/ui/button";
import { ArrowLeftIcon, EditIcon, MoreIcon, TrashIcon } from "@/src/components/ui/icons";
import { Workspace } from "@/src/components/workspace-header";
import { useSop } from "@/src/features/sops/hooks/use-sop";
import { formatRelativeDate } from "@/src/lib/utils";
import { DeleteSopDialog } from "./delete-sop-dialog";
import { SopListSkeleton } from "./sop-list";

export function SopDetailView({ id }: { id: number }) {
  const router = useRouter(); const { sop, status, error } = useSop(id); const [deleteOpen, setDeleteOpen] = useState(false);
  if (status === "loading") return <Workspace><main className="mx-auto max-w-[920px] px-5 py-14 sm:px-8"><div className="mb-10 h-4 w-28 animate-pulse rounded bg-surface-subtle" /><div className="mb-4 h-10 w-3/5 animate-pulse rounded bg-surface-subtle" /><div className="mb-12 h-5 w-4/5 animate-pulse rounded bg-surface-subtle" /><SopListSkeleton /></main></Workspace>;
  if (!sop) return <Workspace><main className="grid min-h-[calc(100vh-64px)] place-items-center px-6 text-center"><div><p className="font-mono text-xs font-medium uppercase tracking-[.14em] text-accent">{status === "not-found" ? "404 / PROCESS" : "LOAD ERROR"}</p><h1 className="mt-3 text-2xl font-semibold tracking-[-.03em]">{status === "not-found" ? "Process not found" : "Couldn’t load this process"}</h1><p className="mt-2 text-sm text-muted-foreground">{status === "not-found" ? "It may have been deleted or moved." : error}</p><ButtonLink href="/dashboard" className="mt-6">Back to processes</ButtonLink></div></main></Workspace>;
  return <Workspace><main className="mx-auto w-full max-w-[920px] px-5 pb-20 pt-8 sm:px-8 sm:pt-12"><div className="flex items-center justify-between"><Link href="/dashboard" className="inline-flex items-center gap-2 rounded-lg text-sm font-medium text-muted-foreground hover:text-foreground"><ArrowLeftIcon />Back to processes</Link><div className="hidden items-center gap-2 sm:flex"><ButtonLink href={`/sops/${sop.id}/edit`} variant="secondary"><EditIcon />Edit</ButtonLink><Button variant="ghost" onClick={() => setDeleteOpen(true)} className="text-destructive hover:bg-destructive-soft"><TrashIcon />Delete</Button></div><details className="relative sm:hidden"><summary className="grid size-9 cursor-pointer list-none place-items-center rounded-lg border border-border-strong bg-surface [&::-webkit-details-marker]:hidden" aria-label="Process actions"><MoreIcon /></summary><div className="absolute right-0 z-20 mt-2 w-36 rounded-[10px] border border-border bg-surface-raised p-1 shadow-[0_12px_30px_var(--shadow-color)]"><Link href={`/sops/${sop.id}/edit`} className="flex items-center gap-2 rounded-md px-2.5 py-2 text-sm hover:bg-surface-subtle"><EditIcon />Edit</Link><button onClick={() => setDeleteOpen(true)} className="flex w-full items-center gap-2 rounded-md px-2.5 py-2 text-sm text-destructive hover:bg-destructive-soft"><TrashIcon />Delete</button></div></details></div>
    <header className="min-w-0 border-b border-border pb-10 pt-10 sm:pt-14"><div className="flex flex-wrap items-center gap-3 font-mono text-xs uppercase tracking-[.12em] text-muted-foreground"><span>{sop.steps.length} {sop.steps.length === 1 ? "step" : "steps"}</span><span className="text-border-strong">/</span><span>{formatRelativeDate(sop.updatedAt)}</span></div><h1 dir="auto" className="mt-4 max-w-3xl break-words text-[2.35rem] font-semibold leading-[1.08] tracking-[-.052em] sm:text-[3.35rem]">{sop.title}</h1>{sop.description && <p dir="auto" className="mt-5 max-w-2xl break-words text-[17px] leading-7 text-muted-foreground">{sop.description}</p>}</header>
    <section className="pt-3" aria-labelledby="steps-title"><h2 id="steps-title" className="sr-only">Procedure steps</h2><ol>{sop.steps.map((step, index) => <li key={step.id} className="grid grid-cols-[44px_minmax(0,1fr)] gap-3 border-b border-border py-7 last:border-0 sm:grid-cols-[72px_minmax(0,1fr)] sm:gap-6 sm:py-9"><span className="font-mono text-[1.55rem] font-medium leading-8 tracking-[-.06em] text-step-number sm:text-[2rem]">{String(index + 1).padStart(2, "0")}</span><p dir="auto" className="min-w-0 max-w-2xl break-words pt-0.5 text-[16px] leading-7 tracking-[-.008em] sm:text-lg sm:leading-8">{step.content}</p></li>)}</ol></section>
    <footer className="mt-10 flex flex-wrap items-center justify-between gap-3 border-t border-border pt-6 text-sm text-muted-foreground"><span>End of process</span><Link href={`/sops/${sop.id}/edit`} className="font-medium text-foreground underline decoration-border-strong underline-offset-4 hover:decoration-foreground">Improve this process</Link></footer>
    <DeleteSopDialog sopId={sop.id} sopTitle={sop.title} open={deleteOpen} onClose={() => setDeleteOpen(false)} onDeleted={() => router.push("/dashboard")} />
  </main></Workspace>;
}
